version: '2'

services:
  tx:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      BITCOIN_HOST: bitcoin
    command: py.test -v
  bitcoin:
    image: ascribe/bitcoin
    volumes:
      -  ./.bitcoin:/root/.bitcoin
    ports:
      - '18332'
      - '18333'
    command: bitcoind -regtest -printtoconsole
