#version: '2'

#services:
tx:
  build: .
  volumes:
    - ./docs:/usr/src/app/docs
    - ./transactions:/usr/src/app/transactions
    - ./tests:/usr/src/app/tests
    - ./pytest.ini:/usr/src/app/pytest.ini
    - ./setup.cfg:/usr/src/app/setup.cfg
    - ./setup.py:/usr/src/app/setup.py
  command: 'true'
  links:
    - bitcoin

bitcoin:
  #image: felixweis/bitcoind
  image: sbellem/docker-bitcoin
  volumes: 
    #- ~/bitcoin-data:/root/.bitcoin
    - ~/bitcoin-data:/data
  ports:
    - '8332'
    - '8333'
  command: bitcoind -regtest -printtoconsole
